##Aluno: Lucas Barbosa dos Santos

##Atividade
Utilizando como base o código 2.2-LinearRegressionIrisNumPy.ipynb,
faça as 3 atividades abaixo. Para submissão, submeta sua resposta no
repositório criado para a disciplina.

Coloque o resultado dentro de uma pasta chamada "Atividade Aula 2.2".

1. Modifique o laço do treinamento via gradiente descendente para guardar em uma
lista, o valor da perda no final de cada época. Após o treinamento,
plote o valor da perda em função da época.

2. Calcule o valor da perda (MSE) da rede com os parâmetros inicializados, sem serem treinados.

3. Coloque os valores dos pesos da solução ótima analítica no modelo da rede e
calcule o valor da perda (MSE) e compare com o valor da perda obtida
pelo método da otimização via gradiente descendente.

In [1]:
#Importação de Pacotes
%matplotlib inline
import matplotlib.pyplot as plt   # para plotting
from sklearn.datasets import load_iris  # para carregar dataset
import numpy as np  # processamento matricial
np.random.seed(1234)

In [2]:
#Leitura dos dados
iris = load_iris()
data = iris.data[iris.target==1,::2]  # comprimento das sépalas e pétalas, indices 0 e 2
x_train = data[:,0:1]
y_train = data[:,1:2]
n_samples = x_train.shape[0]
print('x_train.shape:',x_train.shape, x_train.dtype)
print('y_train.shape:',y_train.shape, y_train.dtype)
print('x_train[:5]:\n', x_train[:5])
print('y_train[:5]:\n', y_train[:5])

x_train.shape: (50, 1) float64
y_train.shape: (50, 1) float64
x_train[:5]:
 [[7. ]
 [6.4]
 [6.9]
 [5.5]
 [6.5]]
y_train[:5]:
 [[4.7]
 [4.5]
 [4.9]
 [4. ]
 [4.6]]


In [3]:
#Normalização dos dados
x_train -= x_train.min()
x_train /= x_train.max()
y_train -= y_train.min()
y_train /= y_train.max()

In [5]:
# Preenchendo x com coluna de 1's para bias
x_train_bias = np.hstack([np.ones(shape=(n_samples,1)), x_train])
x_train_bias

array([[1.        , 1.        ],
       [1.        , 0.71428571],
       [1.        , 0.95238095],
       [1.        , 0.28571429],
       [1.        , 0.76190476],
       [1.        , 0.38095238],
       [1.        , 0.66666667],
       [1.        , 0.        ],
       [1.        , 0.80952381],
       [1.        , 0.14285714],
       [1.        , 0.04761905],
       [1.        , 0.47619048],
       [1.        , 0.52380952],
       [1.        , 0.57142857],
       [1.        , 0.33333333],
       [1.        , 0.85714286],
       [1.        , 0.33333333],
       [1.        , 0.42857143],
       [1.        , 0.61904762],
       [1.        , 0.33333333],
       [1.        , 0.47619048],
       [1.        , 0.57142857],
       [1.        , 0.66666667],
       [1.        , 0.57142857],
       [1.        , 0.71428571],
       [1.        , 0.80952381],
       [1.        , 0.9047619 ],
       [1.        , 0.85714286],
       [1.        , 0.52380952],
       [1.        , 0.38095238],
       [1.

In [6]:
# Classe com o modelo da rede
class Net():
    def __init__(self, n_in, n_out):
        self.w = np.random.uniform(-0.1,0.1,(n_out,n_in)) #inicialização dos parâmetros

    def forward(self, x_bias):
        return x_bias.dot(self.w.T) #^y

In [7]:
# Criando a rede, instanciando o objeto model
model = Net(2,1) # duas entradas (1 + x0) e uma saída y_pred

In [9]:
num_epochs = 100
learning_rate = 0.5
for epoch in range(num_epochs):

    # forward - predict
    y_pred = model.forward(x_train_bias)

    #loss cálculo da função de perda
    loss = np.square(y_pred - y_train).mean()

    # cálculo do gradiente pelas derivadas parciais
    w_grad = (2.0/n_samples) * (x_train_bias.T).dot(x_train_bias.dot(model.w.T) - y_train)

    # gradiente descendente
    model.w = model.w - learning_rate * w_grad.T

    # verbose
    if (epoch+1) % 1 == 0:
        print('Epoch[{}/{}], loss: {:.6f}'
              .format(epoch+1, num_epochs, loss))

Epoch[1/100], loss: 0.469163
Epoch[2/100], loss: 0.058070
Epoch[3/100], loss: 0.030543
Epoch[4/100], loss: 0.028105
Epoch[5/100], loss: 0.027364
Epoch[6/100], loss: 0.026787
Epoch[7/100], loss: 0.026269
Epoch[8/100], loss: 0.025799
Epoch[9/100], loss: 0.025373
Epoch[10/100], loss: 0.024986
Epoch[11/100], loss: 0.024634
Epoch[12/100], loss: 0.024315
Epoch[13/100], loss: 0.024025
Epoch[14/100], loss: 0.023762
Epoch[15/100], loss: 0.023524
Epoch[16/100], loss: 0.023307
Epoch[17/100], loss: 0.023110
Epoch[18/100], loss: 0.022931
Epoch[19/100], loss: 0.022769
Epoch[20/100], loss: 0.022622
Epoch[21/100], loss: 0.022488
Epoch[22/100], loss: 0.022366
Epoch[23/100], loss: 0.022256
Epoch[24/100], loss: 0.022156
Epoch[25/100], loss: 0.022065
Epoch[26/100], loss: 0.021983
Epoch[27/100], loss: 0.021908
Epoch[28/100], loss: 0.021840
Epoch[29/100], loss: 0.021778
Epoch[30/100], loss: 0.021722
Epoch[31/100], loss: 0.021671
Epoch[32/100], loss: 0.021625
Epoch[33/100], loss: 0.021583
Epoch[34/100], loss

In [10]:
# Parâmetros treinados
print(model.w)

[[0.26295353 0.68335641]]


In [11]:
# Avaliação do modelo
loss = np.square(y_pred - y_train).mean()
loss

np.float64(0.021170062593862105)

In [12]:
# Valor ótimo, solução analítica
x = x_train_bias
y = y_train
w_opt = (np.linalg.inv((x.T).dot(x)).dot(x.T)).dot(y)
print(w_opt.T)

[[0.26134159 0.68646976]]


In [13]:
#1
num_epochs = 100
learning_rate = 0.5
losses = []
for epoch in range(num_epochs):

    # forward - predict
    y_pred = model.forward(x_train_bias)

    #loss cálculo da função de perda
    loss = np.square(y_pred - y_train).mean()

    # cálculo do gradiente pelas derivadas parciais
    w_grad = (2.0/n_samples) * (x_train_bias.T).dot(x_train_bias.dot(model.w.T) - y_train)

    # gradiente descendente
    model.w = model.w - learning_rate * w_grad.T

    losses.append(loss)

    # verbose
    if (epoch+1) % 1 == 0:
        print('Epoch[{}/{}], loss: {:.6f}'
              .format(epoch+1, num_epochs, loss))
print(losses)

Epoch[1/100], loss: 0.021170
Epoch[2/100], loss: 0.021170
Epoch[3/100], loss: 0.021170
Epoch[4/100], loss: 0.021170
Epoch[5/100], loss: 0.021170
Epoch[6/100], loss: 0.021170
Epoch[7/100], loss: 0.021170
Epoch[8/100], loss: 0.021170
Epoch[9/100], loss: 0.021170
Epoch[10/100], loss: 0.021170
Epoch[11/100], loss: 0.021170
Epoch[12/100], loss: 0.021170
Epoch[13/100], loss: 0.021170
Epoch[14/100], loss: 0.021170
Epoch[15/100], loss: 0.021170
Epoch[16/100], loss: 0.021170
Epoch[17/100], loss: 0.021170
Epoch[18/100], loss: 0.021170
Epoch[19/100], loss: 0.021170
Epoch[20/100], loss: 0.021170
Epoch[21/100], loss: 0.021170
Epoch[22/100], loss: 0.021170
Epoch[23/100], loss: 0.021169
Epoch[24/100], loss: 0.021169
Epoch[25/100], loss: 0.021169
Epoch[26/100], loss: 0.021169
Epoch[27/100], loss: 0.021169
Epoch[28/100], loss: 0.021169
Epoch[29/100], loss: 0.021169
Epoch[30/100], loss: 0.021169
Epoch[31/100], loss: 0.021169
Epoch[32/100], loss: 0.021169
Epoch[33/100], loss: 0.021169
Epoch[34/100], loss

In [14]:
#2
model = Net(2,1)
print(model.w)
y_pred = model.forward(x_train_bias)
print(y_pred)
loss = np.square(y_pred - y_train).mean()
print(loss)

[[0.03669259 0.04254041]]
[[0.07923299]
 [0.06707859]
 [0.07720726]
 [0.04884699]
 [0.06910432]
 [0.05289846]
 [0.06505286]
 [0.03669259]
 [0.07113006]
 [0.04276979]
 [0.03871832]
 [0.05694992]
 [0.05897566]
 [0.06100139]
 [0.05087272]
 [0.07315579]
 [0.05087272]
 [0.05492419]
 [0.06302712]
 [0.05087272]
 [0.05694992]
 [0.06100139]
 [0.06505286]
 [0.06100139]
 [0.06707859]
 [0.07113006]
 [0.07518153]
 [0.07315579]
 [0.05897566]
 [0.05289846]
 [0.04884699]
 [0.04884699]
 [0.05492419]
 [0.05897566]
 [0.04682125]
 [0.05897566]
 [0.07315579]
 [0.06505286]
 [0.05087272]
 [0.04884699]
 [0.04884699]
 [0.06100139]
 [0.05492419]
 [0.03871832]
 [0.05087272]
 [0.05289846]
 [0.05289846]
 [0.06302712]
 [0.04074405]
 [0.05289846]]
0.3398312818108879


In [15]:
#3
#Solução gradiente
model = Net(2,1)
num_epochs = 100
learning_rate = 0.5
for epoch in range(num_epochs):

    # forward - predict
    y_pred = model.forward(x_train_bias)

    #loss cálculo da função de perda
    loss = np.square(y_pred - y_train).mean()

    # cálculo do gradiente pelas derivadas parciais
    w_grad = (2.0/n_samples) * (x_train_bias.T).dot(x_train_bias.dot(model.w.T) - y_train)

    # gradiente descendente
    model.w = model.w - learning_rate * w_grad.T
print(f"Valores Solução Gradiente:\n w: {model.w} | perda: {loss}")

#Solução ótima
x = x_train_bias
y = y_train
w_opt = (np.linalg.inv((x.T).dot(x)).dot(x.T)).dot(y)
model.w = w_opt.T
# forward - predict
y_pred = model.forward(x_train_bias)

#loss cálculo da função de perda
loss = np.square(y_pred - y_train).mean()

print(f"Valores Solução Ótima:\n w: {model.w} | perda: {loss}")

Valores Solução Gradiente:
 w: [[0.26305351 0.6831633 ]] | perda: 0.02117014425438359
Valores Solução Ótima:
 w: [[0.26134159 0.68646976]] | perda: 0.021169424119097165
